# Generated by Django 2.2.9 on 2020-01-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=32, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('status', models.CharField(blank=True, choices=[('n', 'Not set'), ('a', 'Acquaintances'), ('i', 'Internet'), ('O', 'Outdoor advertising')], default='n', max_length=1, verbose_name='Откуда узнал о мастерской')),
                ('device_type', models.CharField(blank=True, max_length=32, verbose_name='Тип устройство')),
                ('serial_number', models.CharField(blank=True, max_length=32, verbose_name='Серийный номер/IMEI')),
                ('brand', models.CharField(blank=True, max_length=32, verbose_name='Брэнд')),
                ('model', models.CharField(blank=True, max_length=32, verbose_name='Модель')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('appearance', models.CharField(blank=True, max_length=32, verbose_name='Внешний вид')),
                ('password', models.CharField(blank=True, max_length=32, verbose_name='Пароль')),
                ('malfunction', models.TextField(blank=True, verbose_name='Неисправность')),
                ('receiver_notes', models.TextField(blank=True, verbose_name='Заметки приемщика')),
                ('indicative_price', models.CharField(blank=True, max_length=32, verbose_name='Ориентировочная цена')),
                ('quickly', models.BooleanField(verbose_name='Срочно')),
                ('availability_date', models.DateTimeField(null=True)),
                ('receipt_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Поступил')),
                ('executor', models.CharField(blank=True, max_length=32, verbose_name='Выполнитель')),
                ('prepayment', models.CharField(blank=True, max_length=32, verbose_name='Предоплата')),
                ('done', models.BooleanField(verbose_name='Готово')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField(verbose_name='Вердикт / рекомендации клиенту')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Задача')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Работа')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Executor_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Работа')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(verbose_name='Работа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
        ),
    ]
