# Generated by Django 2.2.9 on 2020-02-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='availability_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quickly',
            field=models.BooleanField(default=False, verbose_name='Срочно'),
        ),
    ]
