# Generated by Django 2.2.9 on 2020-02-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200208_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Заметка')),
                ('note_type', models.CharField(choices=[('c', 'Comment'), ('t', 'Task')], default='c', max_length=1, verbose_name='Тип заметки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
