# Generated by Django 2.2.9 on 2020-02-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
