# Generated by Django 2.2.9 on 2020-02-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200210_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdict',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='executor_note',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='verdict',
            field=models.TextField(blank=True, verbose_name='Вердикт / рекомендации клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип устройства'),
        ),
        migrations.DeleteModel(
            name='Executor_notes',
        ),
        migrations.DeleteModel(
            name='Verdict',
        ),
    ]
