# Generated by Django 2.2.9 on 2020-02-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200212_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(verbose_name='Работа')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.CharField(blank=True, max_length=32, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor_note',
            field=models.TextField(blank=True, verbose_name='Комментарий исполнителя'),
        ),
        migrations.DeleteModel(
            name='Completed_work',
        ),
        migrations.AddField(
            model_name='completedwork',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Заказ'),
        ),
    ]
