# Generated by Django 2.2.9 on 2020-02-13 13:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200213_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='warranty',
            field=models.DecimalField(decimal_places=0, default=30, max_digits=4, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appearance',
            field=models.CharField(blank=True, default='Потертости, царапины', max_length=32, verbose_name='Внешний вид'),
        ),
        migrations.AlterField(
            model_name='order',
            name='availability_date',
            field=models.DateTimeField(blank=True, default=main.models.now_plus_5, verbose_name='Срок заказа'),
        ),
    ]
