# Generated by Django 2.2.11 on 2020-04-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200416_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='PdfTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_text', models.TextField(verbose_name='Текст пдф')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Settings', verbose_name='Экземляр настроек')),
            ],
        ),
    ]
