# Generated by Django 2.2.11 on 2020-04-20 09:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pdftemplate_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='pdf_text',
            field=tinymce.models.HTMLField(verbose_name='Текст пдф'),
        ),
    ]
