# Generated by Django 2.2.11 on 2020-04-22 13:01

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200422_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdftemplate',
            options={'verbose_name': 'Пдф шаблон', 'verbose_name_plural': 'Пдф шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_timestamp_path, verbose_name='Изображение')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Settings', verbose_name='Экземпляр настроек')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
