# Generated by Django 2.2.11 on 2020-04-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200423_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='order',
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
